version: '3'

services:
  bbq-landing:
    build: .
    container_name: bbq-landing
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1